### ISSUE TITLE
Downloading MD5 checksum failed

### ISSUE THREAD

**Issue by hanayashiki** [Pelhans/ZASR_tensorflow#1]
```
root@LAPTOP-LMKN11R5:/mnt/d/zasr/ZASR_tensorflow/example/aishell# ./run_data.sh
adsadas 6c58fe97d6afd67202da241e8c28c57d
Downloading http://www.openslr.org/resources/33/data_aishell.tgz ...
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled.
--2018-08-09 16:11:37--  http://www.openslr.org/resources/33/data_aishell.tgz
Resolving www.openslr.org (www.openslr.org)... 46.101.158.64
Connecting to www.openslr.org (www.openslr.org)|46.101.158.64|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15582913665 (15G) [application/x-gzip]
Saving to: ‘/media/nlp/23ACE59C56A55BF3/wav_file/aishell/data_aishell.tgz’

data_aishell.tgz    100%[===================>]  14.51G  8.04MB/s    in 34m 25s

2018-08-09 16:46:02 (7.20 MB/s) - ‘/media/nlp/23ACE59C56A55BF3/wav_file/aishell/data_aishell.tgz’ saved [15582913665/15582913665]


MD5 Chesksum /media/nlp/23ACE59C56A55BF3/wav_file/aishell/data_aishell.tgz ...
Traceback (most recent call last):
  File "data/aishell/aishell.py", line 119, in <module>
    main()
  File "data/aishell/aishell.py", line 115, in main
    manifest_path=args.manifest_prefix)
  File "data/aishell/aishell.py", line 94, in prepare_dataset
    filepath = download(url, md5sum, target_dir)
  File "/mnt/d/zasr/ZASR_tensorflow/data_utils/utility.py", line 76, in download
    raise RuntimeError("MD5 checksum failed.")
```

Is it possible that the downloaded file is really broken or the MD5 checksum itself is wrong? Thanks in advance.

**Comment by Pelhans** [comment]
no, it seems that you didn't change the path to save data_aishell.tgz

**Comment by hanayashiki** [comment]
不好意思我不太明白，我下好了以后是可以看到文件存储在了默认的地址的，这和MD5checksum的计算有什么关系呢？谢谢。

**Comment by Pelhans** [comment]
你可以去存储文件的路径下手动计算一下md5,如果能对上的话文件就应该没问题。

我猜测应该是这个md5计算/media/nlp/23ACE59C56A55BF3/wav_file/aishell/data_aishell.tgz 的md5值，假如这个路径找不到这个文件的话就会计算一个随机的md5值，导致校验问题。
